workflows:
  flutter-workflow:
    name: Flutter CI/CD Pipeline
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test
      - name: Build Android APK
        script: flutter build apk --release
      - name: Build iOS IPA
        script: flutter build ios --release
