workflows:
  default-workflow:
    name: Build Without Docker
    scripts:
      - name: Set Up Environment
        script: |
          apt-get update
          apt-get install -y openjdk-17-jdk maven
      - name: Build Project
        script: mvn clean package
      - name: Run Tests
        script: mvn test
    artifacts:
      - target/*.jar
